export const OPTIONS_COUNT = 4

export const GDG_DIFFICULITY = {
  EASY: "GDG_DIFFICULITY_EASY",
  MEDIUM: "GDG_DIFFICULITY_MEDIUM",
  HARD: "GDG_DIFFICULITY_HARD",
}

export const GDG_MODE = {
  GUESS: "GDG_MODE_GUESS",
  PAIRS: "GDG_MODE_PAIRS",
}

export const GDG_STATUS = {
  INIT: "GDG_STATUS_INIT",
  QUESTION: "GDG_STATUS_QUESTION",
  RESULT: "GDG_STATUS_RESULT",
}
